### PR TITLE
feat: device_setBitMode

### PR DESCRIPTION
**Pull request by ArcherGu**
Add FT_SetBitMode

### CODE REVIEW

**Comment by motla** [comment]
@ArcherGu Great stuff! Well done! Thanks for your contribution. 😉 
I totally missed the Extended API Functions from the doc...
I am quite busy right now but I hope to have a moment this weekend to release a new version with your PR.
Cheers

**Comment by ArcherGu** [comment]
We can refine it together, actually this is the first time I've written node addon and I'm learning from you, lol

**Comment by motla** [comment]
I just looked over the code it seems perfect 😉  
Yeah I spent a lot of time learning Node API with the Promise management, and configuring a project with CMake.js, with testing debugging and everything, on multi-platforms, not the most interesting stuff in the world but I had to do it.
Now I'm pretty happy with the result, it can serve as a good base for developing other native plugins. But I reckon it was exhausting.

**Comment by ArcherGu** [comment]
I'm waiting for you to add FT_SetEventNotification,😀. I haven't used `pthread`, I don't know how to do this😂.

By the way, `libuv` seems to have a close ability to `pthread`. After all, `libuv` has been integrated with `v8`

**Comment by motla** [comment]
Yeah I don't know either, and it seems to be a different approach for each platform... I'm not going in to that sorry 😊 
However to receive data asynchronously and continuously, I guess it's possible by creating a JS async function and to call it without await.

For example (not tested but this may work):
```javascript

import FTDI from 'ftdi-d2xx';

/** Asynchronous receiver function
 * @param {FTDI.FTDI_Device} device 
*/
async function start_receiving (device) {
  while (true) { // you can replace true by an `!abort` global variable and set FTDI RX timeout to something
    console.log("Waiting to receive...");
    const response = await device.read(1);
    console.log("Received one byte:", response);
    // your_callback_function(response);
  }
}

// Main code
const list = await FTDI.getDeviceInfoList();
if(list.length) {
  const device = await FTDI.openDevice(list[0].serial_number);
  console.log("Device open:", device);

  start_receiving(device);

  // ...
  console.log("While receiving, the rest of the code here is still running");
  // ...

} else console.log("No device found");

```

**Comment by ArcherGu** [comment]
This is fine, but I think event-driven callbacks are more elegant and performance-saving. Anyway, thank you very much for your answers.

**Comment by motla** [comment]
Aaah, yes you're right. I thought it was a good solution, but no, as it turns out the `FT_Read` function is pumping all the CPU... inside of it has to be a simple while() that polls for something.
I was too confident about this. Definitely have to implement `FT_SetEventNotification` as you suggest.
I will look at `libuv`, thanks for the tip. However I can't work much on this in short term...
Do you plan to try implement it?

**Comment by ArcherGu** [comment]
I actually kept trying after finishing this PR, but I didn't have C/C++ development experience, I got stuck, and I couldn't implement it in a short period of time.😢

**Comment by ArcherGu** [comment]
I wrote a simple implementation with reference to [node-addon-examples/async_work_thread_safe_function](https://github.com/nodejs/node-addon-examples/tree/main/async_work_thread_safe_function/napi). ~~And only fires once~~, but works. Currently I'm only using apis on Windows.

```c
#include "api/FTDI_Device_setEventNotification.h"
#include "api/FTDI_Device.h"
#include "ftd2xx.h"
#include "utils.h"

typedef struct
{
    napi_async_work work;
    napi_threadsafe_function tsfn;

    HANDLE hEvent;

    // Data passed to execute_callback
    device_instance_data_t *instance_data;
    uint8_t *rx_buffer;

    // Data passed to complete_callback
    FT_STATUS ftStatus;
    DWORD rx_bytes_returned;
} async_data_t;

// This function is called when the rx_buffer can be freed
static void finalize_rx_buffer(napi_env env, void *rx_buffer, void *finalize_hint)
{
    (void)env, (void)finalize_hint; // hide unused parameter warning
    free(rx_buffer);
}

// This function is responsible for converting data coming in from the worker
// thread to napi_value items that can be passed into JavaScript, and for
// calling the JavaScript function.
static void call_js(napi_env env, napi_value js_cb, void *context, void *data)
{
    // This parameter is not used.
    (void)context;

    async_data_t *async_data = (async_data_t *)data;

    // env and js_cb may both be NULL if Node.js is in its cleanup phase, and
    // items are left over from earlier thread-safe calls from the worker thread.
    // When env is NULL, we simply skip over the call into Javascript.
    if (env != NULL)
    {
        napi_value undefined, array_buffer, uint8_array = NULL;

        // Create JavaScript Uint8Array containing the read data
        utils_check(napi_create_external_arraybuffer(env, async_data->rx_buffer, async_data->rx_bytes_returned, finalize_rx_buffer, NULL, &array_buffer));
        utils_check(napi_create_typedarray(env, napi_uint8_array, async_data->rx_bytes_returned, array_buffer, 0, &uint8_array));

        // Retrieve the JavaScript `undefined` value so we can use it as the `this`
        // value of the JavaScript function call.
        utils_check(napi_get_undefined(env, &undefined));

        // Call the JavaScript function
        utils_check(napi_call_function(env, undefined, js_cb, 1, &uint8_array, NULL));
    }
}

// This function runs on a worker thread. It has no access to the JavaScript
// environment except through the thread-safe function.
static void execute_work(napi_env env, void *data)
{
    async_data_t *async_data = (async_data_t *)data;

    // We bracket the use of the thread-safe function by this thread by a call to
    // napi_acquire_threadsafe_function() here, and by a call to
    // napi_release_threadsafe_function() immediately prior to thread exit.
    utils_check(napi_acquire_threadsafe_function(async_data->tsfn));

    DWORD rx_bytes_to_read;

    // Wait for event
#define WAIT_TIME_MILLISECONDS 250
    while (1)
    {
        WaitForSingleObject(async_data->hEvent, WAIT_TIME_MILLISECONDS);
        // Abort if there is no device handle
        if (!async_data->instance_data->ftHandle)
            return;

        async_data->ftStatus = FT_GetQueueStatus(async_data->instance_data->ftHandle, &rx_bytes_to_read);

        if (utils_check(async_data->ftStatus != FT_OK))
            return;

        if (rx_bytes_to_read > 0)
        {
            async_data->rx_buffer = malloc(rx_bytes_to_read);
            if (utils_check(async_data->rx_buffer == NULL, "Malloc failed", "malloc"))
                return;

            async_data->ftStatus = FT_Read(async_data->instance_data->ftHandle, async_data->rx_buffer, rx_bytes_to_read, &(async_data->rx_bytes_returned));

            if (utils_check(async_data->ftStatus != FT_OK))
                return;

            // Initiate the call into JavaScript. The call into JavaScript will not
            // have happened when this function returns, but it will be queued.
            utils_check(napi_call_threadsafe_function(
                async_data->tsfn,
                async_data,
                napi_tsfn_blocking));
        }
    }

    // Indicate that this thread will make no further use of the thread-safe
    // function.
    utils_check(napi_release_threadsafe_function(async_data->tsfn, napi_tsfn_release));
}

// This function runs on the main thread after `ExecuteWork` exits.
static void work_complete(napi_env env, napi_status status, void *data)
{
    async_data_t *async_data = (async_data_t *)data;

    // Clean up the thread-safe function and the work item associated with this
    // run.
    utils_check(napi_release_threadsafe_function(async_data->tsfn, napi_tsfn_release));
    utils_check(napi_delete_async_work(env, async_data->work));

    // Free async instance data structure
    free(async_data);
}

napi_value device_setEventNotification(napi_env env, napi_callback_info info)
{
// Get JavaScript `this` corresponding to this instance of the class and `argc`/`argv` passed to the function
#define NB_ARGS 2          // number of expected arguments
    size_t argc = NB_ARGS; // size of the argv buffer
    napi_value this_arg, argv[NB_ARGS], work_name;
    async_data_t *async_data = malloc(sizeof(async_data_t));
    if (utils_check(async_data == NULL, "Malloc failed", "malloc"))
        return NULL;

    async_data->work = NULL;
    async_data->hEvent = CreateEvent(
        NULL,
        false, // auto-reset event
        false, // non-signalled state
        "");

    utils_check(napi_get_cb_info(env, info, &argc, argv, &this_arg, NULL));
    if (utils_check(argc < NB_ARGS, "Missing argument", "missarg"))
        return NULL;

    // Get the class instance data containing FTDI device handle
    utils_check(napi_unwrap(env, this_arg, (void **)(&async_data->instance_data)));

    // Check the device is open if its handle is still there
    if (utils_check(async_data->instance_data->ftHandle == NULL, "Dead device object", "deadobj"))
        return NULL;

    // Check arguments, and convert JavaScript values to C values
    uint32_t event_mask;
    if (utils_check(
            ((napi_get_value_uint32(env, argv[0], &event_mask) != napi_ok) || (event_mask != FT_EVENT_RXCHAR &&
                                                                               event_mask != FT_EVENT_MODEM_STATUS &&
                                                                               event_mask != FT_EVENT_LINE_STATUS)),
            "Event mask must be FT_EVENT_RXCHAR, FT_EVENT_MODEM_STATUS or FT_EVENT_LINE_STATUS", "wrongarg"))
        return NULL;

    // FT_SetEventNotification
    utils_check(FT_SetEventNotification(async_data->instance_data->ftHandle, (DWORD)event_mask, (PVOID)async_data->hEvent));

    // Create a string to describe this asynchronous operation.
    utils_check(napi_create_string_utf8(env,
                                        "Node-API Thread-safe Call from Async Work Item",
                                        NAPI_AUTO_LENGTH,
                                        &work_name));

    // Convert the callback retrieved from JavaScript into a thread-safe
    // function which we can call from a worker thread.
    napi_value event_handle = argv[1];
    utils_check(napi_create_threadsafe_function(env,
                                                event_handle,
                                                NULL,
                                                work_name,
                                                0,
                                                1,
                                                NULL,
                                                NULL,
                                                NULL,
                                                call_js,
                                                &(async_data->tsfn)));

    // Create an async work item, passing in the addon data, which will give the
    // worker thread access to the above-created thread-safe function.
    utils_check(napi_create_async_work(env,
                                       NULL,
                                       work_name,
                                       execute_work,
                                       work_complete,
                                       async_data,
                                       &(async_data->work)));

    // Queue the work item for execution.
    utils_check(napi_queue_async_work(env, async_data->work));

    return NULL;
}

```

**Pull request merged**
